[package]
name = "yellowstone-grpc-geyser"
version = "1.10.0+solana.1.17.1"
authors = ["Triton One"]
edition = "2021"
description = "Yellowstone gRPC Geyser Plugin"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "config-check"

[dependencies]
anyhow = "1.0.62"
base64 = "0.21.0"
bincode = "1.3.3"
bs58 = "0.4.0"
clap = { version = "4.3.24", features = ["cargo", "derive"] }
crossbeam-channel = "0.5.8"
futures = "0.3.24"
hyper = { version = "0.14.20", features = ["server"] }
lazy_static = "1.4.0"
log = "0.4.17"
prometheus = "0.13.2"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
solana-geyser-plugin-interface = { git = "https://github.com/blockworks-foundation/solana.git", tag = "geyser_send_transaction_results_v1.16.21_new" }
solana-logger = { git = "https://github.com/blockworks-foundation/solana.git", tag = "geyser_send_transaction_results_v1.16.21_new" }
solana-sdk = { git = "https://github.com/blockworks-foundation/solana.git", tag = "geyser_send_transaction_results_v1.16.21_new" }
solana-transaction-status = { git = "https://github.com/blockworks-foundation/solana.git", tag = "geyser_send_transaction_results_v1.16.21_new" }
spl-token-2022 = { version = "0.9.0", features = ["no-entrypoint"] }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros", "time", "fs"] }
tokio-stream = "0.1.11"
tonic = { version = "0.10.2", features = ["gzip", "tls", "tls-roots"] }
tonic-health = "0.10.2"
yellowstone-grpc-proto = { path = "../yellowstone-grpc-proto" }

[build-dependencies]
anyhow = "1.0.62"
cargo-lock = "9.0.0"
git-version = "0.3.5"
vergen = { version = "8.2.1", features = ["build", "rustc"] }
