[package]
name = "yellowstone-grpc-client-simple"
version = "1.10.0+solana.1.17.1"
authors = ["Triton One"]
edition = "2021"
publish = false

[[bin]]
name = "client"

[dependencies]
anyhow = "1.0.62"
backoff = { version = "0.4.0", features = ["tokio"] }
bincode = "1.3.3"
bs58 = "0.4.0"
chrono = "0.4.26"
clap = { version = "4.3.0", features = ["cargo", "derive"] }
env_logger = "0.10.0"
futures = "0.3.24"
hex = "0.4.3"
log = { version = "0.4.14", features = ["std"] }
maplit = "1.0.2"
serde_json = "1.0.86"
solana-sdk = { git = "https://github.com/blockworks-foundation/solana.git", tag = "geyser_send_transaction_results_v1.16.21_new" }
solana-transaction-status = { git = "https://github.com/blockworks-foundation/solana.git", tag = "geyser_send_transaction_results_v1.16.21_new" }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros", "time"] }
yellowstone-grpc-client = { path = "../../yellowstone-grpc-client" }
yellowstone-grpc-proto = { path = "../../yellowstone-grpc-proto" }
